[tool.poetry]
name = "2026-p1-eszy09"
version = "0.1.0"
description = ""
authors = ["Vishal"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
